const images: { [key: string]: string } = {
    '1.webp': require('../components/book/book-wallpaper-stories/1.webp'),
    '2.webp': require('../components/book/book-wallpaper-stories/2.webp'),
    '3.webp': require('../components/book/book-wallpaper-stories/3.webp'),
    '4.webp': require('../components/book/book-wallpaper-stories/4.webp'),
    '5.webp': require('../components/book/book-wallpaper-stories/5.webp'),
    '6.webp': require('../components/book/book-wallpaper-stories/6.webp'),
    '7.webp': require('../components/book/book-wallpaper-stories/7.webp'),
    '8.webp': require('../components/book/book-wallpaper-stories/8.webp'),
    '9.webp': require('../components/book/book-wallpaper-stories/9.webp'),
    '10.webp': require('../components/book/book-wallpaper-stories/10.webp'),
    '11.webp': require('../components/book/book-wallpaper-stories/11.webp'),
    '12.webp': require('../components/book/book-wallpaper-stories/12.webp'),
    '13.webp': require('../components/book/book-wallpaper-stories/13.webp'),
    '14.webp': require('../components/book/book-wallpaper-stories/14.webp'),
    '15.webp': require('../components/book/book-wallpaper-stories/15.webp'),
    '16.webp': require('../components/book/book-wallpaper-stories/16.webp'),
    '17.webp': require('../components/book/book-wallpaper-stories/17.webp'),
    '18.webp': require('../components/book/book-wallpaper-stories/18.webp'),
    '19.webp': require('../components/book/book-wallpaper-stories/19.webp'),
    '20.webp': require('../components/book/book-wallpaper-stories/20.webp'),
    '21.webp': require('../components/book/book-wallpaper-stories/21.webp'),
    '22.webp': require('../components/book/book-wallpaper-stories/22.webp'),
    '23.webp': require('../components/book/book-wallpaper-stories/23.webp'),
    '24.webp': require('../components/book/book-wallpaper-stories/24.webp'),
    '25.webp': require('../components/book/book-wallpaper-stories/25.webp'),
    '26.webp': require('../components/book/book-wallpaper-stories/26.webp'),
    '27.webp': require('../components/book/book-wallpaper-stories/27.webp'),
    '28.webp': require('../components/book/book-wallpaper-stories/28.webp'),
    '29.webp': require('../components/book/book-wallpaper-stories/29.webp'),
    '30.webp': require('../components/book/book-wallpaper-stories/30.webp'),
  };
  
  export default images;